const { contextBridge, ipcRenderer, webUtils } = require('electron');

function invoke(channel, payload) {
  return ipcRenderer.invoke(channel, payload);
}

contextBridge.exposeInMainWorld('nocturne', {
  bootstrap: () => invoke('app:bootstrap'),
  createVault: (password) => invoke('vault:create', password),
  unlock: (password) => invoke('vault:unlock', password),
  recover: (key) => invoke('vault:recover', key),
  quickUnlock: (mode, credential) => invoke('vault:quick-unlock', { mode, credential }),
  lock: () => invoke('vault:lock'),
  snapshot: () => invoke('vault:snapshot'),
  saveEntry: (entry) => invoke('vault:save-entry', entry),
  deleteEntry: (id) => invoke('vault:delete-entry', id),
  saveNote: (note) => invoke('vault:save-note', note),
  deleteNote: (id) => invoke('vault:delete-note', id),
  saveOtp: (entry) => invoke('vault:save-otp', entry),
  deleteOtp: (id) => invoke('vault:delete-otp', id),
  otpCodes: () => invoke('vault:otp-codes'),
  importOtpUri: (uri) => invoke('vault:import-otp-uri', uri),
  importOtpClipboard: () => invoke('vault:import-otp-clipboard'),
  importOtpQr: () => invoke('vault:import-otp-qr'),
  importNotePhotos: (id) => invoke('vault:import-note-photos', id),
  addFolder: (input) => invoke('vault:add-folder', input),
  renameFolder: (id, name) => invoke('vault:rename-folder', { id, name }),
  updateFolderMetadata: (input) => invoke('vault:update-folder-metadata', input),
  moveFolders: (input) => invoke('vault:move-folders', input),
  deleteFolders: (ids) => invoke('vault:delete-folders', ids),
  updateItemMetadata: (input) => invoke('vault:update-item-metadata', input),
  deleteItems: (section, ids) => invoke('vault:delete-items', { section, ids }),
  saveSettings: (settings) => invoke('vault:save-settings', settings),
  verifyMasterPassword: (password) => invoke('vault:verify-master-password', password),
  configureQuickUnlock: (mode, credential, currentPassword) => invoke('vault:quick-configure', { mode, credential, currentPassword }),
  changeMasterPassword: (currentPassword, newPassword) => invoke('vault:change-master-password', { currentPassword, newPassword }),
  destroyVault: (currentPassword) => invoke('vault:destroy', currentPassword),
  exportVaultBackup: (currentPassword) => invoke('vault:export-backup', currentPassword),
  importVaultBackup: (masterPassword) => invoke('vault:import-backup', masterPassword),
  importMedia: (folderId = null) => invoke('vault:import-media', folderId),
  importDocuments: (folderId = null) => invoke('vault:import-documents', folderId),
  importPaths: (files, kind = 'auto', target = {}) => invoke('vault:import-paths', { files: Array.from(files || [], (file) => ({ path: webUtils.getPathForFile(file), name: file.name, type: file.type })), kind, target }),
  consumeExternalImports: (target = {}) => invoke('vault:consume-external-imports', target),
  captureRegion: (folderId = null) => invoke('vault:capture-region', folderId),
  importRecordedAudio: (bytes, name, type, folderId = null) => invoke('vault:import-recorded-audio', { bytes, name, type, folderId }),
  importNoteFromClipboard: (id) => invoke('vault:import-note-clipboard', id),
  deleteMedia: (id) => invoke('vault:delete-media', id),
  renameMedia: (id, name) => invoke('vault:rename-media', { id, name }),
  saveMedia: (id) => invoke('vault:save-media', id),
  previewDocument: (id) => invoke('vault:preview-document', id),
  saveTextDocument: (id, text) => invoke('vault:save-text-document', { id, text }),
  createTextDocument: (name, type, text = '', folderId = null) => invoke('vault:create-text-document', { name, type, text, folderId }),
  restoreDocumentVersion: (documentId, versionId) => invoke('vault:restore-document-version', { documentId, versionId }),
  restoreTrash: (id) => invoke('vault:restore-trash', id),
  previewTrash: (id) => invoke('vault:preview-trash', id),
  purgeTrash: (id) => invoke('vault:purge-trash', id),
  emptyTrash: () => invoke('vault:empty-trash'),
  copyMedia: (id) => invoke('vault:copy-media', id),
  saveRecoveryKey: (key) => invoke('vault:save-recovery-key', key),
  copySecurely: (text, clearAfterSeconds) => invoke('clipboard:write', { text, clearAfterSeconds }),
  recordActivity: () => ipcRenderer.send('session:activity'),
  minimize: () => invoke('window:minimize'),
  maximize: () => invoke('window:maximize'),
  close: () => invoke('window:close'),
  setAutostart: (enabled) => invoke('app:set-autostart', enabled),
  savePreferences: (preferences) => invoke('app:save-preferences', preferences),
  onLocked: (callback) => ipcRenderer.on('vault:locked', (_event, data) => callback(data)),
  onWiped: (callback) => ipcRenderer.on('vault:wiped', () => callback()),
  onPrivacyConceal: (callback) => ipcRenderer.on('privacy:conceal', (_event, value) => callback(Boolean(value))),
  onExternalImportsPending: (callback) => ipcRenderer.on('app:external-imports-pending', (_event, count) => callback(Number(count) || 0)),
});
